services:
  marketing-leads-api:
    build: .
    container_name: marketing-leads-api
    restart: unless-stopped
    environment:      
      DATABASE_URL: ${DATABASE_URL}
      PORT: 3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-iurylenon.rule=Host(`api.iurylenon.com`)"
      - "traefik.http.routers.api-iurylenon.entrypoints=websecure"
      - "traefik.http.routers.api-iurylenon.tls.certresolver=letsencrypt"
      - "traefik.http.services.api-iurylenon-service.loadbalancer.server.port=3000"
    networks:
      - web

networks:
  web:
    external: true